### ISSUE TITLE
replicate

### ISSUE THREAD

**Issue by rLannes** [owenjm/damidseq_pipeline#13]
Hi, 

I have 2 replicate for my condition and 2 replicate for my control. 
how can I use damidseq_pipeline with my replicate?

**Comment by marshall-lab** [comment]
Hi,

Just run the pipeline once per replicate, so that you generate one output bedgraph per replicate.

Unfortunately there isn't an automated way for doing this at present (it's on the todo list).  However, it's very easy to use a shell script to do this (which is one reason why it's never been added):

e.g. (in fish shell):
```
for i in 1 2 3; \
damidseq_pipeline sample_n$i.bam dam_n$i.bam; \
end; \
```

Typically, we tend to align all samples / reps at the same time (with the `--just_align` flag), then process the resulting bams as above.

Hope that helps,
Owen

**Comment by owenjm** [comment]
Well, it took a while, but the todo list finally got todone :) 

 v1.6 now adds in automatic experiment and replicate handling: see the changelog and webpage for more details on this.  There's no longer any need for shell scripts or wrappers (or other even more complicated solutions).

Hope that helps,
Owen
